
run_meryl: true

# k=21 recommended for human
# haploid/diploid input
meryl_kmer_size:
  - 21
# other common values:
# k=15 for winnowmap reads-to-ref
# k=19 for winnowmap contig-to-ref

# count k-mers in homopolymer-
# compressed space
# 1 => yes
# 0 => run both options
# -1 => no
meryl_compress: -1
