
process_singletons: True
process_trios: True

compare_pairwise_by_file: False
compare_pairwise_by_sample: False

# some common file format
# extensions to collect input
# from folders via (recursive)
# glob expansion
input_file_ext:
  - fastq.gz
  - fasta.gz
  - fq.gz
  - fa.gz
  - fna.gz
  - fasta

# for operations that use a minimum
# value for the k-mer multiplicity
# (frequency) to subset a k-mer
# database to a more reliable set
# (fewer error k-mers), force this
# threshold instead of using a
# data-derived one. Setting this
# to -1 deactivates the option.
# Setting this to zero uses all
# k-mers, which should be done
# if the workflow input consists
# of virtually error-free sequence
# data.
force_kmerfreq_threshold: -1

# this output is used in winnowmap
extract_high_freq_kmer: false
high_freq_threshold: 0.9998

# k=21 recommended for human
# haploid/diploid input
meryl_kmer_size:
  - 21
# other common values:
# k=15 for winnowmap reads-to-ref
# k=19 for winnowmap contig-to-ref

# count k-mers in homopolymer-
# compressed space
# 1 => yes
# 0 => run both options
# -1 => no
meryl_compress: -1

# Config options to use reference container
# as part of the pipeline
use_reference_container: false
# If use_reference_container is set to true, the following
# two options must be specified as well in the config

# Existing path to directory with reference container (*.sif) files.
# This option is specific to the execution infrastructure.
# reference_container_store: <PATH>

# List of container names to be used in the pipeline
# reference_container_names:
#   - name1
#   - name2
